//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.28 at 03:58:12 PM CEST 
//

package com.lw2.tp6.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for genderType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="genderType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="gender" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@Entity
@Table(name = "gender_type")
@XmlAccessorType(XmlAccessType.NONE)
public class GenderType {

	@XmlValue
	protected String value;
	@XmlAttribute(name = "gender", required = true)
	protected boolean gender;
	@XmlTransient
	private Long idGenderType;

	public GenderType() {
		super();
	}

	public GenderType(String value, boolean gender) {
		super();
		this.value = value;
		this.gender = gender;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "GENDER_ID", unique = true, nullable = false)
	public Long getIdGenderType() {
		return idGenderType;
	}

	public void setIdGenderType(Long idGenderType) {
		this.idGenderType = idGenderType;
	}

	/**
	 * Gets the value of the value property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	@Column(name = "VALUE")
	public String getValue() {
		return value;
	}

	/**
	 * Sets the value of the value property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Gets the value of the gender property.
	 * 
	 */
	@Column(name = "GENDER")
	public boolean getGender() {
		return gender;
	}

	/**
	 * Sets the value of the gender property.
	 * 
	 */
	public void setGender(boolean value) {
		this.gender = value;
	}

}
